### ISSUE TITLE
1 type C port not working...

### ISSUE THREAD

**Issue by Mifaxav** [pierpaolodimarzo/ThinkPad-T480#13]
When I plug in my phone to the charging port on my t480, everything is fine it detects the phone and all but when I change it to the tb port, it just charges. Any fix? Works on macOS big sur on my machine diff efi

**Comment by Mifaxav** [comment]
nvm it doesn't work on big sur either. Still keeping the issue open as Mac is unable to detect phone on tb port macOS Ventura

**Comment by spaceXrace** [comment]
Same issue with my iPhone, maybe caused by [this](https://www.reddit.com/r/hackintosh/comments/nedmbp/comment/gyfn7yd/?utm_source=share&utm_medium=web2x&context=3)? (USB C / Thunderbolt port only have a USB 3 and no USB 2 identity)

**Comment by Mifaxav** [comment]
Yeah but mine detects as tb
