### ISSUE TITLE
Slepp/Wake Problem

### ISSUE THREAD

**Issue by gilberth** [pierpaolodimarzo/ThinkPad-T480#2]
I have a problem, when the computer goes to sleep it no longer returns to the desktop and stays on a black screen, what could be happening?

**Comment by pierpaolodimarzo** [comment]
![Sleep/Wake](https://user-images.githubusercontent.com/81529971/220886073-6209e00e-f277-43d4-8763-9544e6a1df27.png)

Set the settings as per screen ☺️

**Comment by gilberth** [comment]
panic(cpu 2 caller 0xffffff8023331941): userspace watchdog timeout: no successful checkins from WindowServer in 255 seconds
WindowServer has not exited since first loaded
service: logd, total successful checkins in 450 seconds: 32, last successful checkin: 0 seconds ago
service: WindowServer, total successful checkins in 415 seconds: 16, last successful checkin: 255 seconds ago
service: opendirectoryd, total successful checkins in 450 seconds: 31, last successful checkin: 0 seconds ago
service: configd, total successful checkins in 450 seconds: 31, last successful checkin: 0 seconds ago

Panicked task 0xffffff8b8de7a620: 3 threads: pid 101: watchdogd
Backtrace (CPU 2), panicked thread: 0xffffff8b8ef9db30, Frame : Return Address
0xffffffbcb61df590 : 0xffffff801ffeb38d 
0xffffffbcb61df5e0 : 0xffffff8020158ed6 
0xffffffbcb61df620 : 0xffffff8020148120 
0xffffffbcb61df670 : 0xffffff801ff85951 
0xffffffbcb61df690 : 0xffffff801ffeb66d 
0xffffffbcb61df780 : 0xffffff801ffead19 
0xffffffbcb61df7e0 : 0xffffff80207e07f3 
0xffffffbcb61df8d0 : 0xffffff8023331941 
0xffffffbcb61df8e0 : 0xffffff80233315e0 
0xffffffbcb61df900 : 0xffffff80233306c9 
0xffffffbcb61dfa30 : 0xffffff8020753d4a 
0xffffffbcb61dfb90 : 0xffffff80200ffb29 
0xffffffbcb61dfca0 : 0xffffff801ffc2c99 
0xffffffbcb61dfd50 : 0xffffff801ffdbbd2 
0xffffffbcb61dfdc0 : 0xffffff801ffdc2da 
0xffffffbcb61dfef0 : 0xffffff802012a71a 
0xffffffbcb61dffa0 : 0xffffff801ff85db6 
      Kernel Extensions in backtrace:
         com.apple.driver.watchdog(1.0)[A0D45B98-9CEC-33FB-8E19-3AEBEC002241]@0xffffff802332f000->0xffffff8023331fff

Process name corresponding to current thread (0xffffff8b8ef9db30): watchdogd
Boot args: dk.e1000=0 unfairgva=4

Mac OS version:
22D68

Kernel version:
Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64
Kernel UUID: 10E5D254-4A37-3A2A-B560-E6956A093ADE
roots installed: 0
KernelCache slide: 0x000000001fc00000
KernelCache base:  0xffffff801fe00000
Kernel slide:      0x000000001fcdc000
Kernel text base:  0xffffff801fedc000
__HIB  text base: 0xffffff801fd00000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 450280376469
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x00000068d6cd4c11
  Sleep   : 0x00000049b1036017 0x0000001844474673 0x0000000000000000
  Wake    : 0x0000004b6162a585 0x0000000098a4d876 0x00000049b48aaa50
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space
Zone info:
  Zone map: 0xffffff8059ecf000 - 0xffffffa059ecf000
  . PGZ   : 0xffffff8059ecf000 - 0xffffff805bed0000
  . VM    : 0xffffff805bed0000 - 0xffffff85286cf000
  . RO    : 0xffffff85286cf000 - 0xffffff86c1ecf000
  . GEN0  : 0xffffff86c1ecf000 - 0xffffff8b8e6cf000
  . GEN1  : 0xffffff8b8e6cf000 - 0xffffff905aecf000
  . GEN2  : 0xffffff905aecf000 - 0xffffff95276cf000
  . GEN3  : 0xffffff95276cf000 - 0xffffff99f3ecf000
  . DATA  : 0xffffff99f3ecf000 - 0xffffffa059ecf000
  Metadata: 0xffffffffd9fee000 - 0xfffffffff9fee000
  Bitmaps : 0xfffffffff9fee000 - 0xfffffffffffee000

**Comment by gilberth** [comment]
![image](https://user-images.githubusercontent.com/847492/220997412-14a67510-beb7-4ea1-88b4-deff11361ab3.png)

**Comment by pierpaolodimarzo** [comment]
Reboot and Reset NVRAM

**Comment by gilberth** [comment]
After reset de NVRAM same error  :(

**Comment by gilberth** [comment]
panic(cpu 4 caller 0xffffff801af31941): userspace watchdog timeout: no successful checkins from WindowServer in 264 seconds
WindowServer has not exited since first loaded
service: logd, total successful checkins in 418 seconds: 28, last successful checkin: 0 seconds ago
service: WindowServer, total successful checkins in 384 seconds: 12, last successful checkin: 264 seconds ago
service: opendirectoryd, total successful checkins in 418 seconds: 27, last successful checkin: 0 seconds ago
service: configd, total successful checkins in 418 seconds: 27, last successful checkin: 0 seconds ago

Panicked task 0xffffff99e7198620: 3 threads: pid 101: watchdogd
Backtrace (CPU 4), panicked thread: 0xffffff99e712cb30, Frame : Return Address
0xffffffda2c3b3590 : 0xffffff8017beb38d 
0xffffffda2c3b35e0 : 0xffffff8017d58ed6 
0xffffffda2c3b3620 : 0xffffff8017d48120 
0xffffffda2c3b3670 : 0xffffff8017b85951 
0xffffffda2c3b3690 : 0xffffff8017beb66d 
0xffffffda2c3b3780 : 0xffffff8017bead19 
0xffffffda2c3b37e0 : 0xffffff80183e07f3 
0xffffffda2c3b38d0 : 0xffffff801af31941 
0xffffffda2c3b38e0 : 0xffffff801af315e0 
0xffffffda2c3b3900 : 0xffffff801af306c9 
0xffffffda2c3b3a30 : 0xffffff8018353d4a 
0xffffffda2c3b3b90 : 0xffffff8017cffb29 
0xffffffda2c3b3ca0 : 0xffffff8017bc2c99 
0xffffffda2c3b3d50 : 0xffffff8017bdbbd2 
0xffffffda2c3b3dc0 : 0xffffff8017bdc2da 
0xffffffda2c3b3ef0 : 0xffffff8017d2a71a 
0xffffffda2c3b3fa0 : 0xffffff8017b85db6 
      Kernel Extensions in backtrace:
         com.apple.driver.watchdog(1.0)[A0D45B98-9CEC-33FB-8E19-3AEBEC002241]@0xffffff801af2f000->0xffffff801af31fff

Process name corresponding to current thread (0xffffff99e712cb30): watchdogd
Boot args: dk.e1000=0 unfairgva=4

Mac OS version:
22D68

Kernel version:
Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64
Kernel UUID: 10E5D254-4A37-3A2A-B560-E6956A093ADE
roots installed: 0
KernelCache slide: 0x0000000017800000
KernelCache base:  0xffffff8017a00000
Kernel slide:      0x00000000178dc000
Kernel text base:  0xffffff8017adc000
__HIB  text base: 0xffffff8017900000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 418880573186
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x00000061873a539f
  Sleep   : 0x00000042f24b16e5 0x0000001315321c53 0x0000000000000000
  Wake    : 0x00000043319c853d 0x00000000959da9e6 0x00000042f3699979
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space
Zone info:
  Zone map: 0xffffff804da76000 - 0xffffffa04da76000
  . PGZ   : 0xffffff804da76000 - 0xffffff804fa77000
  . VM    : 0xffffff804fa77000 - 0xffffff851c276000
  . RO    : 0xffffff851c276000 - 0xffffff86b5a76000
  . GEN0  : 0xffffff86b5a76000 - 0xffffff8b82276000
  . GEN1  : 0xffffff8b82276000 - 0xffffff904ea76000
  . GEN2  : 0xffffff904ea76000 - 0xffffff951b276000
  . GEN3  : 0xffffff951b276000 - 0xffffff99e7a76000
  . DATA  : 0xffffff99e7a76000 - 0xffffffa04da76000
  Metadata: 0xffffffd024f0f000 - 0xffffffd044f0f000
  Bitmaps : 0xffffffd044f0f000 - 0xffffffd04af0f000
