### ISSUE TITLE
wifi

### ISSUE THREAD

**Issue by doniprdna** [pierpaolodimarzo/ThinkPad-T480#20]
Thanks for sharing this EFI.
I'm using this efi on t480 i5 8250, with bcm94360ng wifi card installed. Since it should work native, I delete the wifi and bluetooth kext, but I have problem with wifi. I cant connect to new wifi without connecting lan cable first.
And i cant join to wifi that have web login portal.
Is there any solution to this? Thanks

**Comment by Mifaxav** [comment]
Hey there.. 

That should not be happening considering you have a native card. Even im running a similar setup with a T480 and a BCM93452Z card (DW1560). I dont mean to drag you out of this repository but i have uploaded my efi in my repository which is forked by EETagent. Check that out if you want…

**Comment by pierpaolodimarzo** [comment]
I use only Intel Wi-Fi card, I haven't had the opportunity to try native Wi-Fi, but in any case they currently wouldn't work with Sonoma unless via OC Legacy Patcher
