### ISSUE TITLE
Shuts down when connecting to WiFi

### ISSUE THREAD

**Issue by bweh** [pierpaolodimarzo/ThinkPad-T480#22]
Whenever I input the password for WiFi, it freezes and shuts down. I tried replacing with the latest version of AirportItlwm but haven’t gotten it to work.

I was on macOS Monterey 12.6.8
i5-8350U, same wifi card as the one listed in the readme 

any ideas?

**Comment by seargentpepper** [comment]
im empty about ideas but at least my wifi was perfect, same CPU, im in ventura.

**Comment by lriverawong** [comment]
I had a similar issue and the fix was use update to the latest version of `Airportitlwm` - https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.2.0
