### ISSUE TITLE
Backlight - BrightnessKeys not working on the T480 i7 8650U + MX150 variant

### ISSUE THREAD

**Issue by opatotto** [pierpaolodimarzo/ThinkPad-T480#24]
I'm trying to fix some problems with my Backlight - BrightnessKeys that doesn't work, I'm using the thunderbolt and is working fine, but the Intel internal graphics is not detected in some way because on my screens the integrated screen is not detected properly, I followed the dorotania guide:

https://dortania.github.io/Getting-Started-With-ACPI/Laptops/backlight-methods/manual.html

The path of my device is: \_SB_.PCI0.GFX0, and looking to the SSDT-Thinkpad_T480.aml this correspond to the PNLF.

Any suggestion to what I need to look?

**Comment by pierpaolodimarzo** [comment]
You need to change the SSDT to its correct path!
