### ISSUE TITLE
boot problem

### ISSUE THREAD

**Issue by bugraduz** [pierpaolodimarzo/ThinkPad-T480#3]
when ı power on my thinkpad , ı see only black screen after lenovo logo . Opencore boot menu cant show. what is the problem ?

**Comment by gilberth** [comment]
Are you booting from a usb stick?

**Comment by pierpaolodimarzo** [comment]
Boot from USB, after configure the bios

**Comment by pierpaolodimarzo** [comment]
Boot from USB, after configure the bios and Reset NVRAM

**Comment by bugraduz** [comment]
NO, ı copy the efı folder in to my efı drive

**Comment by pierpaolodimarzo** [comment]
At the first use USB Boot, After "Reset NVRAM" and after put the EFI in drive.
