### ISSUE TITLE
Trackpad not working

### ISSUE THREAD

**Issue by altecmak** [pierpaolodimarzo/ThinkPad-T480#4]
Installed Ventura using your EFI, everything seems to work just fine but trackpad is not working. I made sure it is not a hardware issue by testing it in windows, works just fine there.

**Comment by Mifaxav** [comment]
im having trackpad issues on big sur using another efi on the same laptop. please do update me with the fix so i can troubleshoot mine

**Comment by dinels12** [comment]
Same here, i try to use the EFI, but doesn't work the trackpad, and i use it a lot!

**Comment by loll70** [comment]
I don't have that issue. Try update the voodoo stuff

**Comment by pierpaolodimarzo** [comment]
Hi, 
updated efi.
try the new EFI

**Comment by galaxy-nomad** [comment]
> Hi, updated efi. try the new EFI

I'm on Sonoma 14.7.1 and my Trackpad and buttons do not work at all. I'm using your Non Touch EFI-i5.8250u build. Do I need to start from scratch mapping USB ports or something like this? My build is T480 i7 8650U
