### ISSUE TITLE
Device SMBIOS Displayed as Mac on Kaby Lake R

### ISSUE THREAD

**Issue by loll70** [pierpaolodimarzo/ThinkPad-T480#5]
even though i regenerated SMBIOS, the device property is still missing.
My CPU is 8550u.
Can you write a little bit about your merged T480 SSDT?

**Comment by pierpaolodimarzo** [comment]
Hi, 
now you can use the EFI 8550u.

**Comment by loll70** [comment]
The issue is now fixed!
