### ISSUE TITLE
Touchscreen not working

### ISSUE THREAD

**Issue by loll70** [pierpaolodimarzo/ThinkPad-T480#6]
Even when including Voodooi2c and Voodooi2cHID, the touchscreen still doesn't work.
Could you please take a look into this?

**Comment by loll70** [comment]
The touchscreen worked on your forked https://github.com/valnoxy/t480-oc/tree/main/EFI/OC

**Comment by pierpaolodimarzo** [comment]
I added EFIs with Touchscreen support

👍
