### ISSUE TITLE
Color banding issue

### ISSUE THREAD

**Issue by rocker376** [pierpaolodimarzo/ThinkPad-T480#7]
I have color banding issues. Is this fix which is implemented in this EFI is for specific LCD screen model or for all FHD models in T480? I’ve also tried with Skylake GPU spoofing, but it doesn’t work on Ventura, causing boot problems,

**Comment by pierpaolodimarzo** [comment]
Use this guide to create a new EDID with your monitor [Patch _EDID](https://github.com/dreamwhite/patch_edid)
